export const _GMB_DATA = [
    {
        "Store code": "CDRCaseys General Store4218",
        "Business name": "CDReload by Crypto Dispensers",
        "Address line 1": "6432 Asheville Hwy",
        "Address line 2": "",
        "Address line 3": "",
        "Address line 4": "",
        "Address line 5": "",
        "Sub-locality": "",
        "Locality": "Knoxville",
        "Administrative area": "TN",
        "Country / Region": "US",
        "Postal code": 37924,
        "Latitude": "",
        "Longitude": "",
        "Primary phone": "(888) 212-5824",
        "Additional phones": "",
        "Website": "[FILL IN WITH DYNAMIC URL CAN BE CALCULATED IN EXCEL]",
        "Primary category": "Crypto ATM",
        "Additional categories": "ATM",
        "Sunday hours": "06:00AM-10:00PM",
        "Monday hours": "06:00AM-10:00PM",
        "Tuesday hours": "06:00AM-10:00PM",
        "Wednesday hours": "06:00AM-10:00PM",
        "Thursday hours": "06:00AM-10:00PM",
        "Friday hours": "06:00AM-10:00PM",
        "Saturday hours": "06:00AM-10:00PM",
        "Special hours": "",
        "From the business": "Get ready to buy Bitcoin with cash in a new way with CDReload by Crypto Dispensers! Sign up, generate a custom barcode, and add up to $500/transaction and $1500/day at participating stores like CVS, Rite Aid, and Office Depot. Once your funds are credited, you can buy or send Bitcoin instantly. Say goodbye to Bitcoin ATMs and hello to CDReload!",
        "Opening date": "",
        "Logo photo": "https://a.mktgcdn.com/p/7wa2ULU2n6L8pWst0XD3l1igM7pxYkytebbkrf2rqFs/418x418.png",
        "Cover photo": "",
        "Other photos": "",
        "Labels": "Casey's General Store",
        "AdWords location extensions phone": ""
    },
    {
        "Store code": "CDRCaseys General Store4037",
        "Business name": "CDReload by Crypto Dispensers",
        "Address line 1": "13061 Kingston Pike",
        "Address line 2": "",
        "Address line 3": "",
        "Address line 4": "",
        "Address line 5": "",
        "Sub-locality": "",
        "Locality": "Knoxville",
        "Administrative area": "TN",
        "Country / Region": "US",
        "Postal code": 37934,
        "Latitude": "",
        "Longitude": "",
        "Primary phone": "(888) 212-5824",
        "Additional phones": "",
        "Website": "[FILL IN WITH DYNAMIC URL CAN BE CALCULATED IN EXCEL]",
        "Primary category": "Crypto ATM",
        "Additional categories": "ATM",
        "Sunday hours": "05:00AM-12:00PM",
        "Monday hours": "05:00AM-12:00PM",
        "Tuesday hours": "05:00AM-12:00PM",
        "Wednesday hours": "05:00AM-12:00PM",
        "Thursday hours": "05:00AM-12:00PM",
        "Friday hours": "05:00AM-12:00PM",
        "Saturday hours": "05:00AM-12:00PM",
        "Special hours": "",
        "From the business": "Get ready to buy Bitcoin with cash in a new way with CDReload by Crypto Dispensers! Sign up, generate a custom barcode, and add up to $500/transaction and $1500/day at participating stores like CVS, Rite Aid, and Office Depot. Once your funds are credited, you can buy or send Bitcoin instantly. Say goodbye to Bitcoin ATMs and hello to CDReload!",
        "Opening date": "",
        "Logo photo": "https://a.mktgcdn.com/p/7wa2ULU2n6L8pWst0XD3l1igM7pxYkytebbkrf2rqFs/418x418.png",
        "Cover photo": "",
        "Other photos": "",
        "Labels": "Casey's General Store",
        "AdWords location extensions phone": ""
    },
    {
        "Store code": "CDRCaseys General Store4049",
        "Business name": "CDReload by Crypto Dispensers",
        "Address line 1": "701 N Campbell Station Rd",
        "Address line 2": "",
        "Address line 3": "",
        "Address line 4": "",
        "Address line 5": "",
        "Sub-locality": "",
        "Locality": "Knoxville",
        "Administrative area": "TN",
        "Country / Region": "US",
        "Postal code": 37934,
        "Latitude": "",
        "Longitude": "",
        "Primary phone": "(888) 212-5824",
        "Additional phones": "",
        "Website": "[FILL IN WITH DYNAMIC URL CAN BE CALCULATED IN EXCEL]",
        "Primary category": "Crypto ATM",
        "Additional categories": "ATM",
        "Sunday hours": "12:00AM-12:00AM",
        "Monday hours": "12:00AM-12:00AM",
        "Tuesday hours": "12:00AM-12:00AM",
        "Wednesday hours": "12:00AM-12:00AM",
        "Thursday hours": "12:00AM-12:00AM",
        "Friday hours": "12:00AM-12:00AM",
        "Saturday hours": "12:00AM-12:00AM",
        "Special hours": "",
        "From the business": "Get ready to buy Bitcoin with cash in a new way with CDReload by Crypto Dispensers! Sign up, generate a custom barcode, and add up to $500/transaction and $1500/day at participating stores like CVS, Rite Aid, and Office Depot. Once your funds are credited, you can buy or send Bitcoin instantly. Say goodbye to Bitcoin ATMs and hello to CDReload!",
        "Opening date": "",
        "Logo photo": "https://a.mktgcdn.com/p/7wa2ULU2n6L8pWst0XD3l1igM7pxYkytebbkrf2rqFs/418x418.png",
        "Cover photo": "",
        "Other photos": "",
        "Labels": "Casey's General Store",
        "AdWords location extensions phone": ""
    },
    {
        "Store code": "CDRCVS9715",
        "Business name": "CDReload by Crypto Dispensers",
        "Address line 1": "2791 Agoura Rd",
        "Address line 2": "",
        "Address line 3": "",
        "Address line 4": "",
        "Address line 5": "",
        "Sub-locality": "",
        "Locality": "Thousand Oaks",
        "Administrative area": "CA",
        "Country / Region": "US",
        "Postal code": 91361,
        "Latitude": "",
        "Longitude": "",
        "Primary phone": "(888) 212-5824",
        "Additional phones": "",
        "Website": "[FILL IN WITH DYNAMIC URL CAN BE CALCULATED IN EXCEL]",
        "Primary category": "Crypto ATM",
        "Additional categories": "ATM",
        "Sunday hours": "06:00am-11:00pm",
        "Monday hours": "06:00am-11:00pm",
        "Tuesday hours": "06:00am-11:00pm",
        "Wednesday hours": "06:00am-11:00pm",
        "Thursday hours": "06:00am-11:00pm",
        "Friday hours": "06:00am-11:00pm",
        "Saturday hours": "06:00am-11:00pm",
        "Special hours": "",
        "From the business": "Get ready to buy Bitcoin with cash in a new way with CDReload by Crypto Dispensers! Sign up, generate a custom barcode, and add up to $500/transaction and $1500/day at participating stores like CVS, Rite Aid, and Office Depot. Once your funds are credited, you can buy or send Bitcoin instantly. Say goodbye to Bitcoin ATMs and hello to CDReload!",
        "Opening date": "",
        "Logo photo": "https://a.mktgcdn.com/p/7wa2ULU2n6L8pWst0XD3l1igM7pxYkytebbkrf2rqFs/418x418.png",
        "Cover photo": "",
        "Other photos": "",
        "Labels": "CVS",
        "AdWords location extensions phone": ""
    },
    {
        "Store code": "CDRCVS9644",
        "Business name": "CDReload by Crypto Dispensers",
        "Address line 1": "16975 Bear Valley Rd",
        "Address line 2": "",
        "Address line 3": "",
        "Address line 4": "",
        "Address line 5": "",
        "Sub-locality": "",
        "Locality": "Hesperia",
        "Administrative area": "CA",
        "Country / Region": "US",
        "Postal code": 92345,
        "Latitude": "",
        "Longitude": "",
        "Primary phone": "(888) 212-5824",
        "Additional phones": "",
        "Website": "[FILL IN WITH DYNAMIC URL CAN BE CALCULATED IN EXCEL]",
        "Primary category": "Crypto ATM",
        "Additional categories": "ATM",
        "Sunday hours": "08:00am-10:00pm",
        "Monday hours": "08:00am-10:00pm",
        "Tuesday hours": "08:00am-10:00pm",
        "Wednesday hours": "08:00am-10:00pm",
        "Thursday hours": "08:00am-10:00pm",
        "Friday hours": "08:00am-10:00pm",
        "Saturday hours": "08:00am-10:00pm",
        "Special hours": "",
        "From the business": "Get ready to buy Bitcoin with cash in a new way with CDReload by Crypto Dispensers! Sign up, generate a custom barcode, and add up to $500/transaction and $1500/day at participating stores like CVS, Rite Aid, and Office Depot. Once your funds are credited, you can buy or send Bitcoin instantly. Say goodbye to Bitcoin ATMs and hello to CDReload!",
        "Opening date": "",
        "Logo photo": "https://a.mktgcdn.com/p/7wa2ULU2n6L8pWst0XD3l1igM7pxYkytebbkrf2rqFs/418x418.png",
        "Cover photo": "",
        "Other photos": "",
        "Labels": "CVS",
        "AdWords location extensions phone": ""
    },
    {
        "Store code": "CDRCVS9787",
        "Business name": "CDReload by Crypto Dispensers",
        "Address line 1": "3943 San Fernando Rd",
        "Address line 2": "",
        "Address line 3": "",
        "Address line 4": "",
        "Address line 5": "",
        "Sub-locality": "",
        "Locality": "Glendale",
        "Administrative area": "CA",
        "Country / Region": "US",
        "Postal code": 91204,
        "Latitude": "",
        "Longitude": "",
        "Primary phone": "(888) 212-5824",
        "Additional phones": "",
        "Website": "[FILL IN WITH DYNAMIC URL CAN BE CALCULATED IN EXCEL]",
        "Primary category": "Crypto ATM",
        "Additional categories": "ATM",
        "Sunday hours": "12:00AM-12:00AM",
        "Monday hours": "12:00AM-12:00AM",
        "Tuesday hours": "12:00AM-12:00AM",
        "Wednesday hours": "12:00AM-12:00AM",
        "Thursday hours": "12:00AM-12:00AM",
        "Friday hours": "12:00AM-12:00AM",
        "Saturday hours": "12:00AM-12:00AM",
        "Special hours": "",
        "From the business": "Get ready to buy Bitcoin with cash in a new way with CDReload by Crypto Dispensers! Sign up, generate a custom barcode, and add up to $500/transaction and $1500/day at participating stores like CVS, Rite Aid, and Office Depot. Once your funds are credited, you can buy or send Bitcoin instantly. Say goodbye to Bitcoin ATMs and hello to CDReload!",
        "Opening date": "",
        "Logo photo": "https://a.mktgcdn.com/p/7wa2ULU2n6L8pWst0XD3l1igM7pxYkytebbkrf2rqFs/418x418.png",
        "Cover photo": "",
        "Other photos": "",
        "Labels": "CVS",
        "AdWords location extensions phone": ""
    },
    {
        "Store code": "CDRGetGo Gas Station3538",
        "Business name": "CDReload by Crypto Dispensers",
        "Address line 1": "1416 Ety Shops Way NW",
        "Address line 2": "",
        "Address line 3": "",
        "Address line 4": "",
        "Address line 5": "",
        "Sub-locality": "",
        "Locality": "Lancaster",
        "Administrative area": "OH",
        "Country / Region": "US",
        "Postal code": 43130,
        "Latitude": "",
        "Longitude": "",
        "Primary phone": "(888) 212-5824",
        "Additional phones": "",
        "Website": "[FILL IN WITH DYNAMIC URL CAN BE CALCULATED IN EXCEL]",
        "Primary category": "Crypto ATM",
        "Additional categories": "ATM",
        "Sunday hours": "06:00am-09:00pm",
        "Monday hours": "06:00am-09:00pm",
        "Tuesday hours": "06:00am-09:00pm",
        "Wednesday hours": "06:00am-09:00pm",
        "Thursday hours": "06:00am-09:00pm",
        "Friday hours": "06:00am-09:00pm",
        "Saturday hours": "06:00am-09:00pm",
        "Special hours": "",
        "From the business": "Get ready to buy Bitcoin with cash in a new way with CDReload by Crypto Dispensers! Sign up, generate a custom barcode, and add up to $500/transaction and $1500/day at participating stores like CVS, Rite Aid, and Office Depot. Once your funds are credited, you can buy or send Bitcoin instantly. Say goodbye to Bitcoin ATMs and hello to CDReload!",
        "Opening date": "",
        "Logo photo": "https://a.mktgcdn.com/p/7wa2ULU2n6L8pWst0XD3l1igM7pxYkytebbkrf2rqFs/418x418.png",
        "Cover photo": "",
        "Other photos": "",
        "Labels": "GetGo",
        "AdWords location extensions phone": ""
    },
    {
        "Store code": "CDRGetGo Gas Station3379",
        "Business name": "CDReload by Crypto Dispensers",
        "Address line 1": "430 E Waterfront Dr",
        "Address line 2": "",
        "Address line 3": "",
        "Address line 4": "",
        "Address line 5": "",
        "Sub-locality": "",
        "Locality": "Homestead",
        "Administrative area": "PA",
        "Country / Region": "US",
        "Postal code": 15120,
        "Latitude": "",
        "Longitude": "",
        "Primary phone": "(888) 212-5824",
        "Additional phones": "",
        "Website": "[FILL IN WITH DYNAMIC URL CAN BE CALCULATED IN EXCEL]",
        "Primary category": "Crypto ATM",
        "Additional categories": "ATM",
        "Sunday hours": "07:00AM-09:00PM",
        "Monday hours": "07:00AM-09:00PM",
        "Tuesday hours": "07:00AM-09:00PM",
        "Wednesday hours": "07:00AM-09:00PM",
        "Thursday hours": "07:00AM-09:00PM",
        "Friday hours": "07:00AM-09:00PM",
        "Saturday hours": "07:00AM-09:00PM",
        "Special hours": "",
        "From the business": "Get ready to buy Bitcoin with cash in a new way with CDReload by Crypto Dispensers! Sign up, generate a custom barcode, and add up to $500/transaction and $1500/day at participating stores like CVS, Rite Aid, and Office Depot. Once your funds are credited, you can buy or send Bitcoin instantly. Say goodbye to Bitcoin ATMs and hello to CDReload!",
        "Opening date": "",
        "Logo photo": "https://a.mktgcdn.com/p/7wa2ULU2n6L8pWst0XD3l1igM7pxYkytebbkrf2rqFs/418x418.png",
        "Cover photo": "",
        "Other photos": "",
        "Labels": "GetGo",
        "AdWords location extensions phone": ""
    },
    {
        "Store code": "CDRGetGo Gas Station3539",
        "Business name": "CDReload by Crypto Dispensers",
        "Address line 1": "820 W 3rd Ave",
        "Address line 2": "",
        "Address line 3": "",
        "Address line 4": "",
        "Address line 5": "",
        "Sub-locality": "",
        "Locality": "Columbus",
        "Administrative area": "OH",
        "Country / Region": "US",
        "Postal code": 43212,
        "Latitude": "",
        "Longitude": "",
        "Primary phone": "(888) 212-5824",
        "Additional phones": "",
        "Website": "[FILL IN WITH DYNAMIC URL CAN BE CALCULATED IN EXCEL]",
        "Primary category": "Crypto ATM",
        "Additional categories": "ATM",
        "Sunday hours": "12:00AM-12:00AM",
        "Monday hours": "12:00AM-12:00AM",
        "Tuesday hours": "12:00AM-12:00AM",
        "Wednesday hours": "12:00AM-12:00AM",
        "Thursday hours": "12:00AM-12:00AM",
        "Friday hours": "12:00AM-12:00AM",
        "Saturday hours": "12:00AM-12:00AM",
        "Special hours": "",
        "From the business": "Get ready to buy Bitcoin with cash in a new way with CDReload by Crypto Dispensers! Sign up, generate a custom barcode, and add up to $500/transaction and $1500/day at participating stores like CVS, Rite Aid, and Office Depot. Once your funds are credited, you can buy or send Bitcoin instantly. Say goodbye to Bitcoin ATMs and hello to CDReload!",
        "Opening date": "",
        "Logo photo": "https://a.mktgcdn.com/p/7wa2ULU2n6L8pWst0XD3l1igM7pxYkytebbkrf2rqFs/418x418.png",
        "Cover photo": "",
        "Other photos": "",
        "Labels": "GetGo",
        "AdWords location extensions phone": ""
    },
    {
        "Store code": "CDRGiant Eagle4",
        "Business name": "CDReload by Crypto Dispensers",
        "Address line 1": "5055 Library Rd",
        "Address line 2": "",
        "Address line 3": "",
        "Address line 4": "",
        "Address line 5": "",
        "Sub-locality": "",
        "Locality": "Bethel Park",
        "Administrative area": "PA",
        "Country / Region": "US",
        "Postal code": 15102,
        "Latitude": "",
        "Longitude": "",
        "Primary phone": "(888) 212-5825",
        "Additional phones": "",
        "Website": "[FILL IN WITH DYNAMIC URL CAN BE CALCULATED IN EXCEL]",
        "Primary category": "Crypto ATM",
        "Additional categories": "ATM",
        "Sunday hours": "07:00AM-10:00PM",
        "Monday hours": "07:00AM-10:00PM",
        "Tuesday hours": "07:00AM-10:00PM",
        "Wednesday hours": "07:00AM-10:00PM",
        "Thursday hours": "07:00AM-10:00PM",
        "Friday hours": "07:00AM-10:00PM",
        "Saturday hours": "07:00AM-10:00PM",
        "Special hours": "",
        "From the business": "Get ready to buy Bitcoin with cash in a new way with CDReload by Crypto Dispensers! Sign up, generate a custom barcode, and add up to $500/transaction and $1500/day at participating stores like CVS, Rite Aid, and Office Depot. Once your funds are credited, you can buy or send Bitcoin instantly. Say goodbye to Bitcoin ATMs and hello to CDReload!",
        "Opening date": "",
        "Logo photo": "https://a.mktgcdn.com/p/7wa2ULU2n6L8pWst0XD3l1igM7pxYkytebbkrf2rqFs/418x418.png",
        "Cover photo": "",
        "Other photos": "",
        "Labels": "Giant Eagle",
        "AdWords location extensions phone": ""
    },
    {
        "Store code": "CDRGiant Eagle9",
        "Business name": "CDReload by Crypto Dispensers",
        "Address line 1": "6204 Route 30",
        "Address line 2": "",
        "Address line 3": "",
        "Address line 4": "",
        "Address line 5": "",
        "Sub-locality": "",
        "Locality": "Greensburg",
        "Administrative area": "PA",
        "Country / Region": "US",
        "Postal code": 15601,
        "Latitude": "",
        "Longitude": "",
        "Primary phone": "(888) 212-5826",
        "Additional phones": "",
        "Website": "[FILL IN WITH DYNAMIC URL CAN BE CALCULATED IN EXCEL]",
        "Primary category": "Crypto ATM",
        "Additional categories": "ATM",
        "Sunday hours": "07:00AM-09:00PM",
        "Monday hours": "07:00AM-09:00PM",
        "Tuesday hours": "07:00AM-09:00PM",
        "Wednesday hours": "07:00AM-09:00PM",
        "Thursday hours": "07:00AM-09:00PM",
        "Friday hours": "07:00AM-09:00PM",
        "Saturday hours": "07:00AM-09:00PM",
        "Special hours": "",
        "From the business": "Get ready to buy Bitcoin with cash in a new way with CDReload by Crypto Dispensers! Sign up, generate a custom barcode, and add up to $500/transaction and $1500/day at participating stores like CVS, Rite Aid, and Office Depot. Once your funds are credited, you can buy or send Bitcoin instantly. Say goodbye to Bitcoin ATMs and hello to CDReload!",
        "Opening date": "",
        "Logo photo": "https://a.mktgcdn.com/p/7wa2ULU2n6L8pWst0XD3l1igM7pxYkytebbkrf2rqFs/418x418.png",
        "Cover photo": "",
        "Other photos": "",
        "Labels": "Giant Eagle",
        "AdWords location extensions phone": ""
    },
    {
        "Store code": "CDRGiant Eagle8",
        "Business name": "CDReload by Crypto Dispensers",
        "Address line 1": "200 Tarentum Bridge Rd",
        "Address line 2": "",
        "Address line 3": "",
        "Address line 4": "",
        "Address line 5": "",
        "Sub-locality": "",
        "Locality": "New Kensington",
        "Administrative area": "PA",
        "Country / Region": "US",
        "Postal code": 15068,
        "Latitude": "",
        "Longitude": "",
        "Primary phone": "(888) 212-5827",
        "Additional phones": "",
        "Website": "[FILL IN WITH DYNAMIC URL CAN BE CALCULATED IN EXCEL]",
        "Primary category": "Crypto ATM",
        "Additional categories": "ATM",
        "Sunday hours": "07:00AM-10:00PM",
        "Monday hours": "07:00AM-10:00PM",
        "Tuesday hours": "07:00AM-10:00PM",
        "Wednesday hours": "07:00AM-10:00PM",
        "Thursday hours": "07:00AM-10:00PM",
        "Friday hours": "07:00AM-10:00PM",
        "Saturday hours": "07:00AM-10:00PM",
        "Special hours": "",
        "From the business": "Get ready to buy Bitcoin with cash in a new way with CDReload by Crypto Dispensers! Sign up, generate a custom barcode, and add up to $500/transaction and $1500/day at participating stores like CVS, Rite Aid, and Office Depot. Once your funds are credited, you can buy or send Bitcoin instantly. Say goodbye to Bitcoin ATMs and hello to CDReload!",
        "Opening date": "",
        "Logo photo": "https://a.mktgcdn.com/p/7wa2ULU2n6L8pWst0XD3l1igM7pxYkytebbkrf2rqFs/418x418.png",
        "Cover photo": "",
        "Other photos": "",
        "Labels": "Giant Eagle",
        "AdWords location extensions phone": ""
    },
    {
        "Store code": "CDRGiant Martins6282",
        "Business name": "CDReload by Crypto Dispensers",
        "Address line 1": "409 South St",
        "Address line 2": "",
        "Address line 3": "",
        "Address line 4": "",
        "Address line 5": "",
        "Sub-locality": "",
        "Locality": "Front Royal",
        "Administrative area": "VA",
        "Country / Region": "US",
        "Postal code": 22630,
        "Latitude": "",
        "Longitude": "",
        "Primary phone": "(888) 212-5824",
        "Additional phones": "",
        "Website": "[FILL IN WITH DYNAMIC URL CAN BE CALCULATED IN EXCEL]",
        "Primary category": "Crypto ATM",
        "Additional categories": "ATM",
        "Sunday hours": "10:00AM-05:00PM",
        "Monday hours": "09:00AM-08:00PM",
        "Tuesday hours": "09:00AM-08:00PM",
        "Wednesday hours": "09:00AM-08:00PM",
        "Thursday hours": "09:00AM-08:00PM",
        "Friday hours": "09:00AM-08:00PM",
        "Saturday hours": "09:00AM-05:00PM",
        "Special hours": "",
        "From the business": "Get ready to buy Bitcoin with cash in a new way with CDReload by Crypto Dispensers! Sign up, generate a custom barcode, and add up to $500/transaction and $1500/day at participating stores like CVS, Rite Aid, and Office Depot. Once your funds are credited, you can buy or send Bitcoin instantly. Say goodbye to Bitcoin ATMs and hello to CDReload!",
        "Opening date": "",
        "Logo photo": "https://a.mktgcdn.com/p/7wa2ULU2n6L8pWst0XD3l1igM7pxYkytebbkrf2rqFs/418x418.png",
        "Cover photo": "",
        "Other photos": "",
        "Labels": "Giant Martin's",
        "AdWords location extensions phone": ""
    },
    {
        "Store code": "CDRGiant Martins6295",
        "Business name": "CDReload by Crypto Dispensers",
        "Address line 1": "240 Elizabeth Dr",
        "Address line 2": "",
        "Address line 3": "",
        "Address line 4": "",
        "Address line 5": "",
        "Sub-locality": "",
        "Locality": "Stephens City",
        "Administrative area": "VA",
        "Country / Region": "US",
        "Postal code": 22655,
        "Latitude": "",
        "Longitude": "",
        "Primary phone": "(888) 212-5824",
        "Additional phones": "",
        "Website": "[FILL IN WITH DYNAMIC URL CAN BE CALCULATED IN EXCEL]",
        "Primary category": "Crypto ATM",
        "Additional categories": "ATM",
        "Sunday hours": "10:00AM-05:00PM",
        "Monday hours": "09:00AM-08:00PM",
        "Tuesday hours": "09:00AM-08:00PM",
        "Wednesday hours": "09:00AM-08:00PM",
        "Thursday hours": "09:00AM-08:00PM",
        "Friday hours": "09:00AM-08:00PM",
        "Saturday hours": "09:00AM-05:00PM",
        "Special hours": "",
        "From the business": "Get ready to buy Bitcoin with cash in a new way with CDReload by Crypto Dispensers! Sign up, generate a custom barcode, and add up to $500/transaction and $1500/day at participating stores like CVS, Rite Aid, and Office Depot. Once your funds are credited, you can buy or send Bitcoin instantly. Say goodbye to Bitcoin ATMs and hello to CDReload!",
        "Opening date": "",
        "Logo photo": "https://a.mktgcdn.com/p/7wa2ULU2n6L8pWst0XD3l1igM7pxYkytebbkrf2rqFs/418x418.png",
        "Cover photo": "",
        "Other photos": "",
        "Labels": "Giant Martin's",
        "AdWords location extensions phone": ""
    },
    {
        "Store code": "CDRGiant Martins6454",
        "Business name": "CDReload by Crypto Dispensers",
        "Address line 1": "15371 Montanus Dr",
        "Address line 2": "",
        "Address line 3": "",
        "Address line 4": "",
        "Address line 5": "",
        "Sub-locality": "",
        "Locality": "Culpeper",
        "Administrative area": "VA",
        "Country / Region": "US",
        "Postal code": 22701,
        "Latitude": "",
        "Longitude": "",
        "Primary phone": "(888) 212-5824",
        "Additional phones": "",
        "Website": "[FILL IN WITH DYNAMIC URL CAN BE CALCULATED IN EXCEL]",
        "Primary category": "Crypto ATM",
        "Additional categories": "ATM",
        "Sunday hours": "06:00AM-10:00PM",
        "Monday hours": "06:00AM-10:00PM",
        "Tuesday hours": "06:00AM-10:00PM",
        "Wednesday hours": "06:00AM-10:00PM",
        "Thursday hours": "06:00AM-10:00PM",
        "Friday hours": "06:00AM-10:00PM",
        "Saturday hours": "06:00AM-10:00PM",
        "Special hours": "",
        "From the business": "Get ready to buy Bitcoin with cash in a new way with CDReload by Crypto Dispensers! Sign up, generate a custom barcode, and add up to $500/transaction and $1500/day at participating stores like CVS, Rite Aid, and Office Depot. Once your funds are credited, you can buy or send Bitcoin instantly. Say goodbye to Bitcoin ATMs and hello to CDReload!",
        "Opening date": "",
        "Logo photo": "https://a.mktgcdn.com/p/7wa2ULU2n6L8pWst0XD3l1igM7pxYkytebbkrf2rqFs/418x418.png",
        "Cover photo": "",
        "Other photos": "",
        "Labels": "Giant Martin's",
        "AdWords location extensions phone": ""
    },
    {
        "Store code": "CDROffice Depot6",
        "Business name": "CDReload by Crypto Dispensers",
        "Address line 1": "2216 E Harmony Rd",
        "Address line 2": "",
        "Address line 3": "",
        "Address line 4": "",
        "Address line 5": "",
        "Sub-locality": "",
        "Locality": "Fort Collins",
        "Administrative area": "CO",
        "Country / Region": "US",
        "Postal code": 80528,
        "Latitude": "",
        "Longitude": "",
        "Primary phone": "(888) 212-5824",
        "Additional phones": "",
        "Website": "[FILL IN WITH DYNAMIC URL CAN BE CALCULATED IN EXCEL]",
        "Primary category": "Crypto ATM",
        "Additional categories": "ATM",
        "Sunday hours": "10:00AM-06:00PM",
        "Monday hours": "09:00AM-08:00PM",
        "Tuesday hours": "09:00AM-08:00PM",
        "Wednesday hours": "09:00AM-08:00PM",
        "Thursday hours": "09:00AM-08:00PM",
        "Friday hours": "09:00AM-08:00PM",
        "Saturday hours": "10:00AM-07:00PM",
        "Special hours": "",
        "From the business": "Get ready to buy Bitcoin with cash in a new way with CDReload by Crypto Dispensers! Sign up, generate a custom barcode, and add up to $500/transaction and $1500/day at participating stores like CVS, Rite Aid, and Office Depot. Once your funds are credited, you can buy or send Bitcoin instantly. Say goodbye to Bitcoin ATMs and hello to CDReload!",
        "Opening date": "",
        "Logo photo": "https://a.mktgcdn.com/p/7wa2ULU2n6L8pWst0XD3l1igM7pxYkytebbkrf2rqFs/418x418.png",
        "Cover photo": "",
        "Other photos": "",
        "Labels": "Office Depot",
        "AdWords location extensions phone": ""
    },
    {
        "Store code": "CDROffice Depot580",
        "Business name": "CDReload by Crypto Dispensers",
        "Address line 1": "277 E 29th St",
        "Address line 2": "",
        "Address line 3": "",
        "Address line 4": "",
        "Address line 5": "",
        "Sub-locality": "",
        "Locality": "Loveland",
        "Administrative area": "CO",
        "Country / Region": "US",
        "Postal code": 80538,
        "Latitude": "",
        "Longitude": "",
        "Primary phone": "(888) 212-5824",
        "Additional phones": "",
        "Website": "[FILL IN WITH DYNAMIC URL CAN BE CALCULATED IN EXCEL]",
        "Primary category": "Crypto ATM",
        "Additional categories": "ATM",
        "Sunday hours": "10:00AM-06:00PM",
        "Monday hours": "08:00AM-08:00PM",
        "Tuesday hours": "08:00AM-08:00PM",
        "Wednesday hours": "08:00AM-08:00PM",
        "Thursday hours": "08:00AM-08:00PM",
        "Friday hours": "08:00AM-08:00PM",
        "Saturday hours": "09:00AM-07:00PM",
        "Special hours": "",
        "From the business": "Get ready to buy Bitcoin with cash in a new way with CDReload by Crypto Dispensers! Sign up, generate a custom barcode, and add up to $500/transaction and $1500/day at participating stores like CVS, Rite Aid, and Office Depot. Once your funds are credited, you can buy or send Bitcoin instantly. Say goodbye to Bitcoin ATMs and hello to CDReload!",
        "Opening date": "",
        "Logo photo": "https://a.mktgcdn.com/p/7wa2ULU2n6L8pWst0XD3l1igM7pxYkytebbkrf2rqFs/418x418.png",
        "Cover photo": "",
        "Other photos": "",
        "Labels": "Office Depot",
        "AdWords location extensions phone": ""
    },
    {
        "Store code": "CDROffice Depot456",
        "Business name": "CDReload by Crypto Dispensers",
        "Address line 1": "535 S 8th St",
        "Address line 2": "",
        "Address line 3": "",
        "Address line 4": "",
        "Address line 5": "",
        "Sub-locality": "",
        "Locality": "Colorado Springs",
        "Administrative area": "CO",
        "Country / Region": "US",
        "Postal code": 80905,
        "Latitude": "",
        "Longitude": "",
        "Primary phone": "(888) 212-5824",
        "Additional phones": "",
        "Website": "[FILL IN WITH DYNAMIC URL CAN BE CALCULATED IN EXCEL]",
        "Primary category": "Crypto ATM",
        "Additional categories": "ATM",
        "Sunday hours": "10:00AM-06:00PM",
        "Monday hours": "08:00AM-08:00PM",
        "Tuesday hours": "08:00AM-08:00PM",
        "Wednesday hours": "08:00AM-08:00PM",
        "Thursday hours": "08:00AM-08:00PM",
        "Friday hours": "08:00AM-08:00PM",
        "Saturday hours": "09:00AM-07:00PM",
        "Special hours": "",
        "From the business": "Get ready to buy Bitcoin with cash in a new way with CDReload by Crypto Dispensers! Sign up, generate a custom barcode, and add up to $500/transaction and $1500/day at participating stores like CVS, Rite Aid, and Office Depot. Once your funds are credited, you can buy or send Bitcoin instantly. Say goodbye to Bitcoin ATMs and hello to CDReload!",
        "Opening date": "",
        "Logo photo": "https://a.mktgcdn.com/p/7wa2ULU2n6L8pWst0XD3l1igM7pxYkytebbkrf2rqFs/418x418.png",
        "Cover photo": "",
        "Other photos": "",
        "Labels": "Office Depot",
        "AdWords location extensions phone": ""
    },
    {
        "Store code": "CDRRite Aid5891",
        "Business name": "CDReload by Crypto Dispensers",
        "Address line 1": "200 Fairmont Shopping Ctr",
        "Address line 2": "",
        "Address line 3": "",
        "Address line 4": "",
        "Address line 5": "",
        "Sub-locality": "",
        "Locality": "Pacifica",
        "Administrative area": "CA",
        "Country / Region": "US",
        "Postal code": 94044,
        "Latitude": "",
        "Longitude": "",
        "Primary phone": "(888) 212-5825",
        "Additional phones": "",
        "Website": "[FILL IN WITH DYNAMIC URL CAN BE CALCULATED IN EXCEL]",
        "Primary category": "Crypto ATM",
        "Additional categories": "ATM",
        "Sunday hours": "08:00AM-10:00PM",
        "Monday hours": "08:00AM-10:00PM",
        "Tuesday hours": "08:00AM-10:00PM",
        "Wednesday hours": "08:00AM-10:00PM",
        "Thursday hours": "08:00AM-10:00PM",
        "Friday hours": "08:00AM-10:00PM",
        "Saturday hours": "08:00AM-10:00PM",
        "Special hours": "",
        "From the business": "Get ready to buy Bitcoin with cash in a new way with CDReload by Crypto Dispensers! Sign up, generate a custom barcode, and add up to $500/transaction and $1500/day at participating stores like CVS, Rite Aid, and Office Depot. Once your funds are credited, you can buy or send Bitcoin instantly. Say goodbye to Bitcoin ATMs and hello to CDReload!",
        "Opening date": "",
        "Logo photo": "https://a.mktgcdn.com/p/7wa2ULU2n6L8pWst0XD3l1igM7pxYkytebbkrf2rqFs/418x418.png",
        "Cover photo": "",
        "Other photos": "",
        "Labels": "Rite Aid",
        "AdWords location extensions phone": ""
    },
    {
        "Store code": "CDRRite Aid5776",
        "Business name": "CDReload by Crypto Dispensers",
        "Address line 1": "801 Linden Ave",
        "Address line 2": "",
        "Address line 3": "",
        "Address line 4": "",
        "Address line 5": "",
        "Sub-locality": "",
        "Locality": "Carpinteria",
        "Administrative area": "CA",
        "Country / Region": "US",
        "Postal code": 93013,
        "Latitude": "",
        "Longitude": "",
        "Primary phone": "(888) 212-5826",
        "Additional phones": "",
        "Website": "[FILL IN WITH DYNAMIC URL CAN BE CALCULATED IN EXCEL]",
        "Primary category": "Crypto ATM",
        "Additional categories": "ATM",
        "Sunday hours": "08:00AM-10:00PM",
        "Monday hours": "08:00AM-10:00PM",
        "Tuesday hours": "08:00AM-10:00PM",
        "Wednesday hours": "08:00AM-10:00PM",
        "Thursday hours": "08:00AM-10:00PM",
        "Friday hours": "08:00AM-10:00PM",
        "Saturday hours": "08:00AM-10:00PM",
        "Special hours": "",
        "From the business": "Get ready to buy Bitcoin with cash in a new way with CDReload by Crypto Dispensers! Sign up, generate a custom barcode, and add up to $500/transaction and $1500/day at participating stores like CVS, Rite Aid, and Office Depot. Once your funds are credited, you can buy or send Bitcoin instantly. Say goodbye to Bitcoin ATMs and hello to CDReload!",
        "Opening date": "",
        "Logo photo": "https://a.mktgcdn.com/p/7wa2ULU2n6L8pWst0XD3l1igM7pxYkytebbkrf2rqFs/418x418.png",
        "Cover photo": "",
        "Other photos": "",
        "Labels": "Rite Aid",
        "AdWords location extensions phone": ""
    },
    {
        "Store code": "CDRRite Aid6034",
        "Business name": "CDReload by Crypto Dispensers",
        "Address line 1": "1730 S Main St",
        "Address line 2": "",
        "Address line 3": "",
        "Address line 4": "",
        "Address line 5": "",
        "Sub-locality": "",
        "Locality": "Willits",
        "Administrative area": "CA",
        "Country / Region": "US",
        "Postal code": 95490,
        "Latitude": "",
        "Longitude": "",
        "Primary phone": "(888) 212-5827",
        "Additional phones": "",
        "Website": "[FILL IN WITH DYNAMIC URL CAN BE CALCULATED IN EXCEL]",
        "Primary category": "Crypto ATM",
        "Additional categories": "ATM",
        "Sunday hours": "08:00AM-09:00PM",
        "Monday hours": "08:00AM-09:00PM",
        "Tuesday hours": "08:00AM-09:00PM",
        "Wednesday hours": "08:00AM-09:00PM",
        "Thursday hours": "08:00AM-09:00PM",
        "Friday hours": "08:00AM-09:00PM",
        "Saturday hours": "08:00AM-09:00PM",
        "Special hours": "",
        "From the business": "Get ready to buy Bitcoin with cash in a new way with CDReload by Crypto Dispensers! Sign up, generate a custom barcode, and add up to $500/transaction and $1500/day at participating stores like CVS, Rite Aid, and Office Depot. Once your funds are credited, you can buy or send Bitcoin instantly. Say goodbye to Bitcoin ATMs and hello to CDReload!",
        "Opening date": "",
        "Logo photo": "https://a.mktgcdn.com/p/7wa2ULU2n6L8pWst0XD3l1igM7pxYkytebbkrf2rqFs/418x418.png",
        "Cover photo": "",
        "Other photos": "",
        "Labels": "Rite Aid",
        "AdWords location extensions phone": ""
    }
  ]
  
  function _convertData(data) {
    const convertedData = {
      storeCode: data["Store code"],
      businessName: data["Business name"] ? data["Business name"] : null,
      addressLine1: data["Address line 1"] ? data["Address line 1"] : null,
      addressLine2: data["Address line 2"] ? data["Address line 2"] : null,
      addressLine3: data["Address line 3"] ? data["Address line 3"] : null,
      addressLine4: data["Address line 4"] ? data["Address line 4"] : null,
      addressLine5: data["Address line 5"] ? data["Address line 5"] : null,
      subLocality: data["Sub-locality"] ? data["Sub-locality"] : null,
      locality: data["Locality"] ? data["Locality"] : null,
      administrativeArea: data["Administrative area"] ? data["Administrative area"] : null,
      countryRegion: data["Country / Region"] ? data["Country / Region"] : null,
      postalCode: data["Postal code"].toString() ? data["Postal code"].toString() : null,
      latitude: data["Latitude"] ? data["Latitude"] : null,
      longitude: data["Longitude"] ? data["Longitude"] : null,
      primaryPhone: data["Primary phone"] ? data["Primary phone"] : null,
      additionalPhones: data["Additional phones"] ? data["Additional phones"] : null,
      website: data["Website"] ? data["Website"] : null,
      primaryCategory: data["Primary category"],
      additionalCategories: data["Additional categories"] ? data["Additional categories"] : null,
      sundayHours: data["Sunday hours"] ? data["Sunday hours"] : null,
      mondayHours: data["Monday hours"] ? data["Monday hours"] : null,
      tuesdayHours: data["Tuesday hours"] ? data["Tuesday hours"] : null,
      wednesdayHours: data["Wednesday hours"] ? data["Wednesday hours"] : null,
      thursdayHours: data["Thursday hours"] ? data["Thursday hours"] : null,
      fridayHours: data["Friday hours"] ? data["Friday hours"] : null,
      saturdayHours: data["Saturday hours"] ? data["Saturday hours"] : null,
      specialHours: data["Special hours"] ? data["Special hours"] : null,
      openingDate: data["Opening date"] ? data["Opening date"] : null,
      logoPhoto: data["Logo photo"] ? data["Logo photo"] : null,
      coverPhoto: data["Cover photo"] ? data["Cover photo"] : null,
      otherPhotos: data["Other photos"] ? data["Other photos"] : null,
      labels: data["Labels"] ? data["Labels"] : null,
      adWordsLocationExtensionsPhone: data["AdWords location extensions phone"] ? data["AdWords location extensions phone"] : null,
    };
  
    return convertedData;
  }
  
  async function _createLocation(data) {
    const convertedData = _convertData(data);
  
    const location = await prisma.location.create({
      data: convertedData,
    });
  
    console.log(convertedData)
  
  }
  
  
  async function _createLocations(data) {
    const locations = [];
    for (const locationData of data) {
      const location = await _createLocation(locationData);
      locations.push(location);
    }
    return locations;
  }
    // const locationstomake = await _createLocations(_GMB_DATA);